function simpletikz(directory, figname, varargin)
% Do not use with supblots. Use the latex package subfig instead
[~, ~] = mkdir(directory, 'figures');
[~, ~] = mkdir(directory, 'figdata');
cleanfigure();
matlab2tikz('filename', sprintf('%s/figures/%s.tikz', directory, figname),...
    'showInfo', false,...
    'externalData', false,...
    'dataPath', sprintf('%s/figdata/', directory),...
    'relativeDataPath', 'figdata',...
    'noSize', true,...
    'parseStrings', false,...
    varargin{:});

end